// flow-typed signature: 56788b572264d516b18823eb5695e821
// flow-typed version: <<STUB>>/to-utf-8_v^1.3.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'to-utf-8'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'to-utf-8' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'to-utf-8/cli' {
  declare module.exports: any;
}

declare module 'to-utf-8/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'to-utf-8/cli.js' {
  declare module.exports: $Exports<'to-utf-8/cli'>;
}
declare module 'to-utf-8/index' {
  declare module.exports: $Exports<'to-utf-8'>;
}
declare module 'to-utf-8/index.js' {
  declare module.exports: $Exports<'to-utf-8'>;
}
declare module 'to-utf-8/test.js' {
  declare module.exports: $Exports<'to-utf-8/test'>;
}
